# PBS flags
queue: normal
project: v45
walltime: 05:00:00
ncpus: 1477
mem: 2900GB
jobname: SOUP15

# Model config
model: mom
shortpath: /short/e14
exe: fms_MOM_SIS_tvvar.x
input:
     - /short/e14/rmh561/mom/archive/MOM_HeatDiag_kb3seg/restart100
     - SOwinds
     - mom025/mask_1920
     - gfdl_nyf_1080_clean
restart_freq: 1

# Collate:
collate:
#     glob: False
#     enable: true
     queue: express
     memory: 4GB
     walltime: 04:00:00
#     mpi: true
     ncpus: 4
#     threads: 2
     flags: -n4 -z -m -r
     exe: /short/v45/aph502/mom/bin/mppnccombine
#     restart: true

# Misc
stacksize: unlimited
mpirun: --mca mtl mxm
qsub_flags: -lother=hyperthread -W umask=027
